#pragma config(Motor,  port2,           CHFrontRight,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           CHFrontLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CHBackLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           CHBackRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Shared/Competition.h"
//1 = right side
//0 = left side
int autonomousMode = 0;

void forward (int time){
	motor[CHFrontRight] = 256;
	motor[CHFrontLeft] = 256;
	motor[CHBackRight] = 256;
	motor[CHBackLeft] = 256;
	wait1Msec(time);
}

void backward (int time){
	motor[CHFrontRight] = -256;
	motor[CHFrontLeft] = -256;
	motor[CHBackRight] = -256;
	motor[CHBackLeft] = -256;
	wait1Msec(time);
}

void turnLeft (int time){
	motor[CHFrontRight] = 256;
	motor[CHFrontLeft] = -256;
	motor[CHBackRight] = 256;
	motor[CHBackLeft] = -256;
	wait1Msec(time);
}

void turnRight (int time){
	motor[CHFrontRight] = -256;
	motor[CHFrontLeft] = 256;
	motor[CHBackRight] = -256;
	motor[CHBackLeft] = 256;
	wait1Msec(time);
}

void autonomous() {
	if (autonomousMode == 0) {
		turnRight(200);
		forward(600);
		turnLeft(355);
		forward(1000);
	} else if (autonomousMode == 1){
		turnLeft(200);
		forward(600);
		turnRight(355);
		forward(1000);
		}
}

void joystick() {
	while (true) {
		motor[CHFrontRight] = vexRT[Ch2];
		motor[CHFrontLeft] = vexRT[Ch3];
		motor[CHBackRight] = vexRT[Ch2];
		motor[CHBackLeft] = vexRT[Ch3];
	}
}
