#pragma config(Motor,  port2,           CHFrontRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           CHFrontLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           CHBackRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CHBackLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           SULeft,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           SURight,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Wrist,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Shared/Competition.h"

//robot controls
void joystick() {
	while (true) {
		motor[CHFrontRight] = vexRT[Ch2];
		motor[CHFrontLeft] = vexRT[Ch3];
		motor[CHBackRight] = vexRT[Ch2];
		motor[CHBackLeft] = vexRT[Ch3];
		motor[SURight] = vexRT[Btn6UXmtr2];
		motor[SULeft] = vexRT[Btn6UXmtr2];
		motor[Claw] = vexRT[Btn5DXmtr2];
		motor[Wrist] = vexRT[Btn5UXmtr2];
	}


} n

task main(){
joystick();
}

/*steps to do
1. clamp claw on preload cone DONE
2. turn 45 degrees to the right DONE
3. move forward 4 feet
4. drop the cone on the mobile goal
5. pick up mobile goal
6. turn 180 degrees counterclockwise
7. move forward 4 feet
8. deposit mobile goal in 5 point zone
*/
